name: braille_app
description: Aplicación Flutter para control de dispositivos Braille ESP32 vía BLE
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Bluetooth Low Energy
  flutter_blue_plus: ^1.32.12
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # UI Components
  animated_splash_screen: ^1.3.0
  
  # Utilities
  flutter_dotenv: ^5.1.0
  vibration: ^3.1.4
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  
  assets:
    - .env
